# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: zh

pipeline:
  - name: JiebaTokenizer # Tokenizer specialized for Chinese texts.
    dictionary_path: "jieba_userdict.txt" # Use the library to split texts into words.
  - name: CountVectorsFeaturizer # Converts text input into a sparse vector of word counts.
    analyzer: "char_wb" # Tokenize into character n-grams instead of word n-grams.
    min_ngram: 1
    max_ngram: 4
  - name: RegexEntityExtractor # Extract entities using regular expression.
    case_sensitive: false
    use_lookup_tables: true
    use_regexes: true
  - name: DIETClassifier # Classify intents and extract entities from user messages. (Crucial for extracting entities)
    epochs: 300
    batch_size: 64
    learning_rate: 0.001
    entity_recognition: true
    intent_classification: true
    evaluate_on_number_of_examples: 20
    evaluate_every_number_of_epochs: 10
    constrain_similarities: True
  - name: EntitySynonymMapper # Map different synonyms of entities to a single canonical value.
  - name: ResponseSelector # Handle frequently asked questions.
    epochs: 100
    retrieval_intent: faq # only activate when detects intent with the prefix of "faq".

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
