CREATE TABLE hotel_rooms (
  id BINARY(16) NOT NULL PRIMARY KEY,
  room_number INT(11) AUTO_INCREMENT NOT NULL,
  room_type VARCHAR(255) NOT NULL,
  room_capacity INT(11) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  availability BOOLEAN NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);